name: PyGLImER
channels:
- conda-forge
dependencies:
  - basemap
  - geographiclib
  - h5py
  - joblib
  - matplotlib
  - numpy
  - obspy
  - pandas
  - pathlib
  - plotly
  - psutil
  - python=3.8
  - scipy
  - pip
  - tqdm
  - flake8
  - pip:
    - sphinx
    - sphinx-rtd-theme
    - pytest
    - -e .
