name: PyGLImER
channels:
  - conda-forge
dependencies:
  - basemap
  - cartopy
  - colorama
  - dill
  - geographiclib
  - joblib
  - matplotlib
  - numpy
  - obspy>=1.3
  - OWSLib
  - pandas
  - pip
  - plotly
  - prov
  - psutil
  - pyasdf
  - pytest
  - python>=3.7
  - scipy<1.9
  - tqdm
  - flake8
  - pyvista
  - pyyaml
  - pip:
    - global-land-mask
    - sphinx<6.0
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinx-gallery
    - jinja2<3.1
    - -e .