name: PyGLImER
dependencies:
  - basemap
  - geographiclib
  - h5py
  - joblib
  - matplotlib
  - numpy
  - obspy
  - pandas
  - pathlib
  - plotly
  - psutil
  - python=3.8
  - scipy
  - pip
  - tqdm
  - flake8
  - vtk
  - pyqt=5
  - mayavi
  - pip:
    - sphinx
    - sphinx-rtd-theme
    - pytest
    - -e .