name: PyGLImER-dev
channels:
  - conda-forge
dependencies:
  - basemap
  - cartopy
  - colorama
  - dill
  - geographiclib
  - joblib
  - matplotlib
  - numpy
  - obspy
  - pandas
  - pathlib
  - pip
  - plotly
  - prov
  - psutil
  - pyasdf
  - pytest
  - python=3.8
  - scipy
  - tqdm
  - flake8
  - pip:
    - sphinx
    - sphinx-rtd-theme