name: PyGLImER
channels:
  - conda-forge
dependencies:
  - basemap
  - cartopy
  - colorama
  - dill
  - geographiclib
  - joblib
  - matplotlib
  - numpy<1.22
  - obspy
  - OWSLib
  - pandas
  - pip
  - plotly
  - prov
  - psutil
  - pyasdf
  - pytest
  - python=3.8
  - scipy
  - tqdm
  - flake8
  - pyvista
  - pyyaml
  - pip:
    - global-land-mask
    - sphinx<4.0
    - pydata-sphinx-theme
    - sphinx-copybutton
    - -e .